name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/emqx/emqx-builder/5.0-14:1.13.3-24.2.1-1-ubuntu20.04

    steps:
    - uses: actions/checkout@v2
    - name: Create Plugin Project
      run: |
        mkdir -p ~/.config/rebar3/templates
        cp -r . ~/.config/rebar3/templates
        cd /tmp
        rebar3 new emqx-plugin my_emqx_plugin
    - name: Xref
      run: make -C /tmp/my_emqx_plugin xref
    - name: Make release
      run: make -C /tmp/my_emqx_plugin rel
